import java.util.ArrayList;
import java.util.List;
import java.util.StringJoiner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }
    public String bestCharge(List<String> inputs) {
        String[] Strings=new String[]{"============= Order details =============\n",
                "-----------------------------------\n","Promotion used:\n",
                "==================================="};
        StringJoiner result=new StringJoiner("");
        final int[] priceSum = {0};
        final int[] SOME_ITEM_HALF = {0};
        result.add(Strings[0]);
        for (String inputsString:inputs) {
            this.itemRepository.findAll().stream().filter(item -> item.getName() == inputsString).forEach(item -> {
                result.add(item + " = " + item.getPrice()*(inputsString.indexOf(inputsString.length()-1)) + " yuan\n");
                priceSum[0] +=(int)(item.getPrice()*(inputsString.indexOf(inputsString.length()-1)));
                SOME_ITEM_HALF[0]=(int)(item.getPrice()*(inputsString.indexOf(inputsString.length()-1)));
                salesPromotionRepository.findAll().forEach(SalesPromotion->{if(SalesPromotion.getRelatedItems().contains(item)){
                    SOME_ITEM_HALF[0] -=(int) (item.getPrice()/2*(inputsString.indexOf(inputsString.length()-1)));
                }});
                if (inputsString == inputs.get(inputs.size() - 1)) {
                    result.add(Strings[1]);
                }
            });
        }
        int BUY_30_SAVE_6=priceSum[0];
        while (BUY_30_SAVE_6>30){
            BUY_30_SAVE_6-=6;
        }
        if (30 > priceSum[0]){
            result.add("Total："+priceSum[0]+" yuan\n");
        }else if (BUY_30_SAVE_6<=SOME_ITEM_HALF[0]){
            result.add(Strings[2]);
            result.add("满30减6 yuan，saving "+(priceSum[0]-BUY_30_SAVE_6)+" yuan\n");
        }else {
            result.add(Strings[2]);
            result.add("Half price for certain dishes (Braised chicken，Cold noodles)，saving "+(priceSum[0]-SOME_ITEM_HALF[0])+" yuan\n");
        }
        result.add(Strings[3]);
        //StringJoiner result=new StringJoiner("+");
        return result.toString();
        //TODO: write code here
    }
}
