import java.util.ArrayList;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }
    public String bestCharge(List<String> inputs) {
        String[] Strings=new String[]{"============= Order details =============\n",
                "-----------------------------------\n","-----------------------------------\n",
                "==================================="};
        List<String> result=new ArrayList<>();
        result.add(Strings[0]);
        int i=1;
        for (String inputsString:inputs) {
            this.itemRepository.findAll().stream().filter(item -> item.getName() == inputsString).forEach(item -> {
                result.add(item + " = " + item.getPrice() + " yuan\n");
                if (inputsString == inputs.get(inputs.size() - 1)) {
                    result.add(Strings[i]);
                }
            });
        }
        //TODO: write code here
    }
}
